package nutc.sot.farm_quest.exception;

public enum QuestErrorCode {
    GAME_NOT_FOUND,
    QUEST_NOT_FOUND,
    QUEST_NOT_AVAILABLE,
    QUEST_NOT_STARTED,
    LOCATION_REQUIRED,
    LOCATION_NOT_FOUND,
    LOCATION_ACCURACY_TOO_LOW,
    LOCATION_TOO_FAR,
    GPS_PERMISSION_REQUIRED,
    AI_RIDDLE_NOT_AVAILABLE,
    AI_RIDDLE_MESSAGE_EMPTY,
    AI_RIDDLE_ALREADY_COMPLETED,
    QUEST_LOCATION_NOT_VERIFIED,
    AI_PROVIDER_UNAVAILABLE,
    RAG_RETRIEVAL_FAILED,
    COUPON_NOT_FOUND,
    COUPON_NOT_OWNED,
    COUPON_EXPIRED,
    COUPON_ALREADY_CONSUMED,
    COUPON_NOT_AVAILABLE,
    COUPON_DUPLICATE_ISSUE,
    MERCHANT_NOT_FOUND,
    KNOWLEDGE_DOCUMENT_NOT_FOUND,
    ADMIN_INVALID_REQUEST,
    ADMIN_RESOURCE_CONFLICT
}
