package nutc.sot.farm_quest.exception;

public enum QuestErrorCode {
    GAME_NOT_FOUND,
    QUEST_NOT_FOUND,
    QUEST_NOT_AVAILABLE,
    QUEST_NOT_STARTED,
    LOCATION_REQUIRED,
    LOCATION_ACCURACY_TOO_LOW,
    LOCATION_TOO_FAR,
    GPS_PERMISSION_REQUIRED,
    AI_RIDDLE_NOT_AVAILABLE,
    AI_RIDDLE_MESSAGE_EMPTY,
    AI_RIDDLE_ALREADY_COMPLETED,
    QUEST_LOCATION_NOT_VERIFIED,
    AI_PROVIDER_UNAVAILABLE,
    RAG_RETRIEVAL_FAILED
}
